server:
  port: 8081
  servlet:
    context-path: /api
    session:
      timeout: "P30D"
      cookie:
        same-site: none
        secure: true

spring:
  redis:
    host: 192.168.3.117
    port: 6379
    database: 1
    main:
      allow-circular-references: true

  application:
    name: tuguang-api
    # 默认 dev 环境
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.117:3306/template?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  config:
    activate:
      on-profile:
        - dev
    # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
